import Foundation

/// Decides whether something that appeared on the clipboard may be recorded.
///
/// The important half of this feature. A clipboard history catches every
/// password, token and one-time code that passes through - so the rules that
/// keep it out are not a setting, they are wired in.
enum PasteboardPolicy {

    /// The convention from nspasteboard.org. Password managers mark what they
    /// put on the clipboard with these, and a well-behaved clipboard history
    /// leaves those items alone. 1Password and Bitwarden both do this.
    static let refusedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        // Marks content a program generated itself - including our own writes.
        "org.nspasteboard.AutoGeneratedType"
    ]

    /// `types` are the pasteboard's declared types, `source` the bundle
    /// identifier of the frontmost app at the moment the change was noticed.
    ///
    /// About `source`: macOS does not say who put something on the clipboard.
    /// The frontmost app is a good guess and almost always right, but it is a
    /// guess - the settings must not present it as a guarantee.
    static func shouldRecord(types: [String],
                             source: String?,
                             excludedApps: Set<String>) -> Bool {
        guard !types.contains(where: refusedTypes.contains) else { return false }
        guard let source, !source.isEmpty else { return true }
        return !excludedApps.contains(source)
    }
}
